### ISSUE TITLE
初めのいーっぽ！

### ISSUE THREAD

**Issue by yaakiyu** [yaakiyu/Chatting-space#1]
知らんけどREADME.md読めばわかる。

**Comment by yaakiyu** [comment]
ついにここをSNSとして使い始めたわwww

**Comment by tasuren** [comment]
kusa

**Comment by yaakiyu** [comment]
tasuren が あらわれた！
コマンド?
- 他の人を呼ぶ
- 他の人を呼ぶ
- 他の人を呼ぶ

**Comment by yaakiyu** [comment]
誰呼ぼうかな

**Comment by yaakiyu** [comment]
そういや自分が開いたPRの中でcloseされたのが2つだけってことに気がついた
しかも両方とも自分から「やべミスった」って消してる

**Comment by tasuren** [comment]
kusa

**Comment by tuna2134** [comment]
どうも

**Comment by tuna2134** [comment]
どうも

**Comment by yaakiyu** [comment]
どうも

**Comment by yaakiyu** [comment]
最近3DSハックしたwww
楽しいwww

**Comment by yaakiyu** [comment]
3DSのカセットをGodMode9ってハックツールで特殊フォーマットに移動して、
FBIってツール(名前がアメリカンなのは内緒)でSDカードにインストールする。
そしてNintendoの出している「セーブデータをカセットからダウンロード版に移行」っていう無料アプリでデータを移行すれば終了。
まぁつまり、カセットゲームをカセットなしで遊べるようにしたってことですね()

**Comment by tasuren** [comment]
Nice

**Comment by tasuren** [comment]
Hey
僕とyaakiyuにしか見えないとこ作ってくれない？

**Comment by yaakiyu** [comment]
いいよ
どうやって作るか知らんけど

**Comment by tuna2134** [comment]
プライベートりぽじすとり

**Comment by yaakiyu** [comment]
@tasuren 作って招待しといたよ

**Comment by tasuren** [comment]
Thx

**Comment by tasuren** [comment]
Hey, Discordまたしばらく見れない感じ？

**Comment by aic-6301** [comment]
どうも(だれ

**Comment by tasuren** [comment]
kusa

**Comment by tuna2134** [comment]
暇じゃな

**Comment by yaakiyu** [comment]
そうじゃな

**Comment by yaakiyu** [comment]
いやそうでもないか
RT関連で忙しいんじゃ(

**Comment by tuna2134** [comment]
がんばれー

**Comment by gx1285** [comment]
こんにちは

**Comment by yaakiyu** [comment]
こんちゃ

**Comment by yaakiyu** [comment]
https://github.com/RT-Team/old-rt/commit/4aaee834dfd41eec074fb4b9431d81f0ef1628ec
懐かしい。そして汚い。()

**Comment by tuna2134** [comment]
Yaakiyuくん。。。
RTの開発大変だね()

**Comment by yaakiyu** [comment]
そんなでもない
学校の息抜きになってる()

**Comment by yaakiyu** [comment]
マジで暇
なぜならば
みんな学校総合体育大会に行くとかで
PC部の我ら引きこもり組は学校で自習しろって言われてるから。
自習するものなくって
タブレットでRT作りまくってる()

**Comment by yaakiyu** [comment]
さて
明日から
修学旅行行ってきます()

**Comment by tasuren** [comment]
Nice

**Comment by yaakiyu** [comment]
やばい今週の木金テストだ()

**Comment by yaakiyu** [comment]
もうあれから半年か

**Comment by gx1285** [comment]
もう12月だ
